# Generated by Django 6.0.4 on 2026-04-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='区域名称')),
                ('zone_type', models.CharField(choices=[('forward', '正向区域'), ('reverse', '反向区域')], default='forward', max_length=20, verbose_name='区域类型')),
                ('primary_dns', models.GenericIPAddressField(blank=True, null=True, verbose_name='主DNS服务器')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DNS区域',
                'verbose_name_plural': 'DNS区域',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='记录名称')),
                ('record_type', models.CharField(choices=[('A', 'A (IPv4地址)'), ('AAAA', 'AAAA (IPv6地址)'), ('CNAME', 'CNAME (别名)'), ('PTR', 'PTR (指针)'), ('MX', 'MX (邮件交换)'), ('TXT', 'TXT (文本)'), ('NS', 'NS (名称服务器)')], default='A', max_length=10, verbose_name='记录类型')),
                ('value', models.TextField(verbose_name='记录值')),
                ('ttl', models.IntegerField(default=3600, help_text='生存时间，默认3600秒(1小时)', verbose_name='TTL(秒)')),
                ('linked_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='关联IP地址')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=20, verbose_name='状态')),
                ('priority', models.IntegerField(blank=True, default=0, help_text='MX记录优先级', null=True, verbose_name='优先级')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dnsmgr.dnszone', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': 'DNS记录',
                'verbose_name_plural': 'DNS记录',
                'ordering': ['name'],
                'unique_together': {('zone', 'name', 'record_type')},
            },
        ),
    ]
