# Generated by Django 6.0.4 on 2026-04-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_forward', models.BooleanField(default=True, help_text='启用后，本地无记录的域名将转发到上游DNS服务器查询', verbose_name='启用外部转发')),
                ('forwarders', models.CharField(default='8.8.8.8, 114.114.114.114', help_text='多个IP用逗号分隔，如: 8.8.8.8, 114.114.114.114', max_length=500, verbose_name='外部转发DNS地址')),
                ('listen_port', models.IntegerField(default=53, help_text='UDP监听端口，默认53', verbose_name='监听端口')),
                ('default_ttl', models.IntegerField(default=3600, verbose_name='默认TTL(秒)')),
                ('listen_address', models.GenericIPAddressField(default='0.0.0.0', help_text='监听的网卡地址，0.0.0.0表示所有接口', verbose_name='监听地址')),
                ('enable_cache', models.BooleanField(default=True, help_text='缓存外部查询结果，提高响应速度', verbose_name='启用缓存')),
                ('cache_ttl', models.IntegerField(default=300, help_text='外部查询结果的缓存时间', verbose_name='缓存TTL(秒)')),
            ],
            options={
                'verbose_name': 'DNS设置',
                'verbose_name_plural': 'DNS设置',
            },
        ),
    ]
