# Generated by Django 6.0.4 on 2026-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmgr', '0002_add_dns_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(db_index=True, max_length=255, verbose_name='查询域名')),
                ('query_type', models.CharField(default='A', max_length=10, verbose_name='查询类型')),
                ('client_ip', models.GenericIPAddressField(db_index=True, verbose_name='客户端IP')),
                ('result_source', models.CharField(choices=[('local', '本地解析'), ('forward', '外部转发'), ('cache', '缓存命中'), ('nxdomain', 'NXDOMAIN'), ('servfail', 'SERVFAIL')], db_index=True, default='local', max_length=20, verbose_name='结果来源')),
                ('answer_data', models.TextField(blank=True, help_text='存储解析结果的IP/域名等信息', verbose_name='响应数据')),
                ('rcode', models.IntegerField(default=0, help_text='0=NOERR, 3=NXDOMAIN, 2=SERVFAIL', verbose_name='响应码')),
                ('response_time_ms', models.FloatField(default=0, verbose_name='响应耗时(ms)')),
                ('query_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='查询时间')),
            ],
            options={
                'verbose_name': 'DNS解析日志',
                'verbose_name_plural': 'DNS解析日志',
                'ordering': ['-query_time'],
                'indexes': [models.Index(fields=['-query_time'], name='dnsmgr_dnsq_query_t_5a9a37_idx'), models.Index(fields=['query_name'], name='dnsmgr_dnsq_query_n_12eb84_idx'), models.Index(fields=['client_ip'], name='dnsmgr_dnsq_client__45b13e_idx'), models.Index(fields=['result_source'], name='dnsmgr_dnsq_result__bc6029_idx'), models.Index(fields=['query_type'], name='dnsmgr_dnsq_query_t_6f2b79_idx')],
            },
        ),
    ]
