# Generated by Django 6.0.4 on 2026-04-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmgr', '0003_add_dns_query_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='probe_port',
            field=models.IntegerField(blank=True, help_text='关联服务探测端口，创建时自动探测该IP:Port的可达性', null=True, verbose_name='探测端口'),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('invalid', '无效')], default='enabled', max_length=20, verbose_name='状态'),
        ),
    ]
