# Generated by Django 6.0.4 on 2026-04-17 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmgr', '0004_add_probe_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('target', models.CharField(max_length=255, verbose_name='目标地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('interval', models.IntegerField(default=10, verbose_name='探测间隔(秒)')),
                ('status', models.CharField(choices=[('running', '运行中'), ('paused', '已暂停'), ('stopped', '已停止')], default='running', max_length=20, verbose_name='运行状态')),
                ('total_probes', models.IntegerField(default=0, verbose_name='总探测次数')),
                ('reachable_count', models.IntegerField(default=0, verbose_name='可达次数')),
                ('timeout_count', models.IntegerField(default=0, verbose_name='超时次数')),
                ('error_count', models.IntegerField(default=0, verbose_name='异常次数')),
                ('last_status', models.CharField(blank=True, default='', max_length=20, verbose_name='最近状态')),
                ('last_latency', models.FloatField(blank=True, null=True, verbose_name='最近延迟(ms)')),
                ('last_message', models.CharField(blank=True, default='', max_length=200, verbose_name='最近消息')),
                ('history', models.TextField(blank=True, default='[]', help_text='JSON数组，存最近30条探测结果摘要', verbose_name='历史记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probe_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '探测任务',
                'verbose_name_plural': '探测任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
