# Generated by Django 6.0.4 on 2026-04-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmgr', '0005_add_probetask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dnsrecord',
            unique_together={('zone', 'name', 'record_type', 'priority')},
        ),
    ]
