# Generated by Django 5.2.13 on 2026-04-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64, verbose_name='服务名称')),
                ('status', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='服务状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='最近检测时间')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='响应耗时')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详情')),
            ],
            options={
                'verbose_name': '服务健康检查',
                'verbose_name_plural': '服务健康检查',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='配置值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
