#!/usr/bin/env bash
set -euo pipefail

BIND_VERSION="9.16.23"

# 是否自动开放防火墙 DNS 服务
OPEN_FIREWALL="${OPEN_FIREWALL:-yes}"

# 是否锁定版本。默认不锁定，避免影响后续系统安全更新。
ENABLE_VERSIONLOCK="${ENABLE_VERSIONLOCK:-no}"

# 允许递归查询的内网地址段，按需修改
ALLOW_RECURSION='127.0.0.1; 10.0.0.0/8; 172.16.0.0/12; 192.168.0.0/16;'

# 可选上游转发 DNS。
# 使用示例：
# FORWARDERS="223.5.5.5; 114.114.114.114;" bash install_bind_9_16_23_rhel9.sh
FORWARDERS="${FORWARDERS:-}"

BACKUP_DIR="/root/named_backup_$(date +%F_%H%M%S)"

log() {
    echo -e "\033[1;32m[$(date '+%F %T')] $*\033[0m"
}

warn() {
    echo -e "\033[1;33m[WARN] $*\033[0m"
}

die() {
    echo -e "\033[1;31m[ERROR] $*\033[0m" >&2
    exit 1
}

if [[ "$EUID" -ne 0 ]]; then
    die "请使用 root 用户执行本脚本。"
fi

if [[ ! -r /etc/os-release ]]; then
    die "无法识别系统版本，未找到 /etc/os-release。"
fi

. /etc/os-release

OS_MAJOR="${VERSION_ID%%.*}"

if [[ "$OS_MAJOR" != "9" ]]; then
    die "当前系统是 ${PRETTY_NAME:-unknown}，本脚本只适配 Red Hat/Rocky/AlmaLinux 9。"
fi

case " ${ID:-} ${ID_LIKE:-} " in
    *rhel*|*rocky*|*almalinux*|*centos*|*fedora*)
        log "当前系统：${PRETTY_NAME}"
        ;;
    *)
        warn "当前系统为 ${PRETTY_NAME:-unknown}，不是典型 RHEL 9 兼容发行版，请谨慎执行。"
        ;;
esac

log "刷新 DNF 缓存"
dnf makecache -y

log "检查当前仓库是否存在 bind ${BIND_VERSION}"
if ! dnf --showduplicates list bind 2>/dev/null | awk '{print $2}' | grep -qE "(^|:)${BIND_VERSION}-"; then
    echo
    warn "当前启用仓库中未发现 bind ${BIND_VERSION}。当前可见版本如下："
    dnf --showduplicates list bind || true
    echo
    die "请检查 BaseOS/AppStream 仓库、RHEL 订阅、Rocky 镜像源是否可用。"
fi

log "安装 BIND ${BIND_VERSION} 及常用工具"
dnf install -y \
    "bind-${BIND_VERSION}*" \
    "bind-utils-${BIND_VERSION}*" \
    "bind-dnssec-utils-${BIND_VERSION}*"

log "验证 named 版本"
named -v

if ! named -v | grep -q "${BIND_VERSION}"; then
    die "当前 named 版本不是 ${BIND_VERSION}，请检查软件源。"
fi

log "备份原有配置到 ${BACKUP_DIR}"
mkdir -p "${BACKUP_DIR}"

for file in /etc/named.conf /etc/named.rfc1912.zones /etc/named.root.key; do
    if [[ -e "$file" ]]; then
        cp -a "$file" "${BACKUP_DIR}/"
    fi
done

log "准备目录权限"
mkdir -p /var/named/data
mkdir -p /var/named/dynamic
mkdir -p /var/named/slaves
mkdir -p /run/named
mkdir -p /var/log/named

chown root:named /var/named
chmod 750 /var/named

chown -R named:named /var/named/data /var/named/dynamic /var/named/slaves /run/named /var/log/named
chmod 750 /var/named/data /var/named/dynamic /var/named/slaves /run/named /var/log/named

if [[ ! -f /var/named/named.ca ]]; then
    warn "未发现 /var/named/named.ca，尝试从 internic 下载根提示文件。"
    curl -fsSL -o /var/named/named.ca https://www.internic.net/domain/named.root || \
        die "下载 named.ca 失败，请检查服务器网络。"
    chown root:named /var/named/named.ca
    chmod 640 /var/named/named.ca
fi

if [[ -n "${FORWARDERS}" ]]; then
    FORWARDERS_BLOCK="forwarders { ${FORWARDERS} };"
else
    FORWARDERS_BLOCK=""
fi

log "生成 /etc/named.conf"

cat > /etc/named.conf <<EOF_CONF
//
// /etc/named.conf
// Generated by install_bind_9_16_23_rhel9.sh
//

acl "internal_networks" {
    ${ALLOW_RECURSION}
};

options {
    listen-on port 53 { any; };
    listen-on-v6 port 53 { any; };

    directory       "/var/named";
    dump-file       "/var/named/data/cache_dump.db";
    statistics-file "/var/named/data/named_stats.txt";
    memstatistics-file "/var/named/data/named_mem_stats.txt";
    secroots-file   "/var/named/data/named.secroots";
    recursing-file  "/var/named/data/named.recursing";

    allow-query     { any; };

    recursion yes;
    allow-recursion { internal_networks; };
    allow-query-cache { internal_networks; };

    dnssec-validation yes;

    managed-keys-directory "/var/named/dynamic";
    pid-file "/run/named/named.pid";
    session-keyfile "/run/named/session.key";

    ${FORWARDERS_BLOCK}

    include "/etc/crypto-policies/back-ends/bind.config";
};

logging {
    channel default_debug {
        file "data/named.run";
        severity dynamic;
    };
};

zone "." IN {
    type hint;
    file "named.ca";
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
EOF_CONF

chown root:named /etc/named.conf
chmod 640 /etc/named.conf

log "恢复 SELinux 上下文"
restorecon -Rv /etc/named.conf /var/named /run/named /var/log/named 2>/dev/null || true

log "检查 BIND 配置"
named-checkconf -z /etc/named.conf

log "启动 named 并设置开机自启"
systemctl enable --now named

log "处理防火墙"
if [[ "${OPEN_FIREWALL}" == "yes" ]] && systemctl is-active --quiet firewalld; then
    firewall-cmd --permanent --add-service=dns
    firewall-cmd --reload
    log "已开放防火墙 DNS 服务。"
else
    warn "firewalld 未运行或 OPEN_FIREWALL!=yes，未修改防火墙。"
fi

if [[ "${ENABLE_VERSIONLOCK}" == "yes" ]]; then
    warn "启用 versionlock 可能会阻止后续安全更新，请确认这是你的预期。"
    if ! rpm -q python3-dnf-plugin-versionlock >/dev/null 2>&1; then
        dnf install -y python3-dnf-plugin-versionlock || true
    fi

    if dnf versionlock --help >/dev/null 2>&1; then
        dnf versionlock add bind bind-utils bind-libs bind-dnssec-utils bind-license || true
    else
        warn "versionlock 插件不可用，已跳过版本锁定。"
    fi
fi

log "查看 named 服务状态"
systemctl --no-pager --full status named || true

log "本机解析测试"
dig @127.0.0.1 localhost A +short || true
dig @127.0.0.1 . NS +short || true

echo
log "BIND ${BIND_VERSION} 安装完成"
echo "named 版本：$(named -v)"
echo "配置文件：/etc/named.conf"
echo "数据目录：/var/named"
echo "日志目录：/var/log/named"
echo "服务管理：systemctl status|restart|stop named"
echo "配置检查：named-checkconf -z /etc/named.conf"