# Generated by Django 6.0.4 on 2026-04-16 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, unique=True, verbose_name='主机名')),
                ('device_name', models.CharField(blank=True, max_length=200, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('server', '服务器'), ('pc', 'PC'), ('laptop', '笔记本'), ('printer', '打印机'), ('switch', '交换机'), ('router', '路由器'), ('firewall', '防火墙'), ('camera', '摄像头'), ('ap', '无线AP'), ('storage', '存储设备'), ('other', '其他')], default='pc', max_length=50, verbose_name='设备类型')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='管理员')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='MAC地址')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='操作系统')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='ipam.ipaddress', verbose_name='关联IP地址')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='ipam.region', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主接口')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='devices.device', verbose_name='所属设备')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interface', to='ipam.ipaddress', verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '设备接口',
                'verbose_name_plural': '设备接口',
            },
        ),
    ]
