# Generated by Django 6.0.4 on 2026-04-16 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='区域编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField(unique=True, verbose_name='VLAN ID')),
                ('name', models.CharField(max_length=100, verbose_name='VLAN名称')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='用途')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlans', to='ipam.region', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLAN',
                'ordering': ['vlan_id'],
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='子网名称')),
                ('cidr', models.CharField(max_length=50, unique=True, verbose_name='网段地址')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关地址')),
                ('prefix_len', models.IntegerField(verbose_name='掩码位数')),
                ('purpose', models.CharField(choices=[('office', '办公网'), ('server', '服务器网'), ('monitor', '监控网'), ('guest', '访客网'), ('management', '管理网'), ('storage', '存储网'), ('dmz', 'DMZ区'), ('other', '其他')], default='other', max_length=50, verbose_name='用途')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='ipam.region', verbose_name='所属区域')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='ipam.vlan', verbose_name='所属VLAN')),
            ],
            options={
                'verbose_name': '子网',
                'verbose_name_plural': '子网',
                'ordering': ['cidr'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('status', models.CharField(choices=[('available', '空闲'), ('allocated', '已分配'), ('reserved', '保留'), ('conflict', '冲突'), ('disabled', '禁用')], default='available', max_length=20, verbose_name='状态')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('device_name', models.CharField(blank=True, max_length=200, verbose_name='设备名称')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='使用人')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='设备类型')),
                ('binding_type', models.CharField(choices=[('static', '静态绑定'), ('dhcp', 'DHCP分配')], default='static', max_length=20, verbose_name='绑定方式')),
                ('dns_linked', models.BooleanField(default=False, verbose_name='DNS关联状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ips', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='ipam.subnet', verbose_name='所属子网')),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
                'ordering': ['ip_address'],
                'unique_together': {('ip_address', 'subnet')},
            },
        ),
    ]
