# Generated by Django 5.2.13 on 2026-04-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhcp', '0001_initial'),
        ('dns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='地址空间名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='地址空间编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '地址空间',
                'verbose_name_plural': '地址空间',
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, max_length=32, verbose_name='MAC 地址')),
                ('status', models.CharField(choices=[('available', '可用'), ('used', '已使用'), ('reserved', '预留'), ('dhcp_dynamic', 'DHCP 动态分配'), ('dhcp_reserved', 'DHCP 固定分配'), ('disabled', '禁用')], default='available', max_length=32, verbose_name='状态')),
                ('usage_type', models.CharField(blank=True, max_length=64, verbose_name='用途')),
                ('owner', models.CharField(blank=True, max_length=64, verbose_name='使用人')),
                ('department', models.CharField(blank=True, max_length=64, verbose_name='部门')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dhcp_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dhcp.dhcpreservation', verbose_name='DHCP保留地址')),
                ('dns_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dns.dnsrecord', verbose_name='DNS记录')),
            ],
            options={
                'verbose_name': 'IP 地址',
                'verbose_name_plural': 'IP 地址',
            },
        ),
        migrations.CreateModel(
            name='IPAddressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('old_status', models.CharField(blank=True, max_length=32, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=32, verbose_name='新状态')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='ipam.ipaddress', verbose_name='IP 地址')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': 'IP 使用历史',
                'verbose_name_plural': 'IP 使用历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=64, verbose_name='CIDR')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关')),
                ('netmask', models.CharField(blank=True, max_length=64, verbose_name='掩码')),
                ('vlan_id', models.IntegerField(blank=True, null=True, verbose_name='VLAN ID')),
                ('vlan_name', models.CharField(blank=True, max_length=64, verbose_name='VLAN 名称')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='位置')),
                ('usage_type', models.CharField(blank=True, max_length=64, verbose_name='用途')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用'), ('planned', '规划中')], default='enabled', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('address_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subnets', to='ipam.addressspace', verbose_name='地址空间')),
            ],
            options={
                'verbose_name': '网段',
                'verbose_name_plural': '网段',
                'unique_together': {('address_space', 'cidr')},
            },
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='ipam.subnet', verbose_name='网段'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_address'], name='ipam_ipaddr_ip_addr_4ee374_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['status'], name='ipam_ipaddr_status_b5df62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('subnet', 'ip_address')},
        ),
    ]
