# Generated by Django 6.0.4 on 2026-04-16 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('ipam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('scan_types', models.CharField(default='ping', help_text='逗号分隔: ping,port,arp', max_length=100, verbose_name='扫描类型')),
                ('ports', models.CharField(blank=True, default='22,80,443', max_length=500, verbose_name='端口')),
                ('schedule', models.CharField(choices=[('manual', '手动触发'), ('hourly', '每小时'), ('daily', '每天'), ('weekly', '每周')], default='manual', max_length=20, verbose_name='调度周期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次执行')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次执行')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_rules', to='ipam.subnet', verbose_name='目标子网')),
            ],
            options={
                'verbose_name': '发现规则',
                'verbose_name_plural': '发现规则',
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('ping', 'Ping 探测'), ('port', '端口扫描'), ('arp', 'ARP 扫描'), ('full', '综合扫描')], default='ping', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '正在执行'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('target_type', models.CharField(choices=[('subnet', '子网'), ('range', 'IP范围'), ('single', '单个IP')], default='subnet', max_length=20, verbose_name='目标类型')),
                ('start_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='起始IP')),
                ('end_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='结束IP')),
                ('ping_count', models.IntegerField(default=3, help_text='每个IP发送的ICMP包数量', verbose_name='Ping次数')),
                ('ping_timeout', models.FloatField(default=1.0, verbose_name='超时时间(秒)')),
                ('ports', models.CharField(blank=True, default='22,80,443,3389', help_text='逗号分隔，如: 22,80,443 或 1-1000', max_length=500, verbose_name='扫描端口')),
                ('port_scan_type', models.CharField(choices=[('connect', 'TCP连接'), ('syn', 'SYN扫描')], default='connect', max_length=20, verbose_name='扫描类型')),
                ('concurrent', models.IntegerField(default=50, help_text='同时扫描的主机数', verbose_name='并发数')),
                ('total_targets', models.IntegerField(default=0, verbose_name='总目标数')),
                ('scanned_count', models.IntegerField(default=0, verbose_name='已扫描数')),
                ('online_count', models.IntegerField(default=0, verbose_name='在线主机数')),
                ('offline_count', models.IntegerField(default=0, verbose_name='离线主机数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注/错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('subnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_tasks', to='ipam.subnet', verbose_name='目标子网')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('ping_success', models.BooleanField(default=False, verbose_name='Ping成功')),
                ('ping_avg_time', models.FloatField(blank=True, null=True, verbose_name='平均延迟(ms)')),
                ('ping_min_time', models.FloatField(blank=True, null=True, verbose_name='最小延迟(ms)')),
                ('ping_max_time', models.FloatField(blank=True, null=True, verbose_name='最大延迟(ms)')),
                ('packet_loss', models.FloatField(default=100.0, verbose_name='丢包率(%)')),
                ('ttl', models.IntegerField(blank=True, null=True, verbose_name='TTL')),
                ('reverse_dns', models.CharField(blank=True, max_length=255, verbose_name='反解域名')),
                ('open_ports', models.JSONField(blank=True, default=dict, verbose_name='开放端口')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='厂商')),
                ('is_new_host', models.BooleanField(default=False, help_text='系统中未登记的主机', verbose_name='新发现主机')),
                ('status_conflict', models.BooleanField(default=False, help_text='系统显示离线但实际在线，或反之', verbose_name='状态冲突')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('matched_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_results', to='devices.device', verbose_name='匹配设备')),
                ('matched_ip_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_results', to='ipam.ipaddress', verbose_name='匹配IP记录')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ipam.scantask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '扫描结果',
                'verbose_name_plural': '扫描结果',
                'ordering': ['ip_address'],
                'unique_together': {('task', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='ProbeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP地址')),
                ('is_online', models.BooleanField(verbose_name='是否在线')),
                ('ping_time', models.FloatField(blank=True, null=True, verbose_name='延迟(ms)')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('task', '扫描任务'), ('manual', '手动探测'), ('schedule', '定时任务')], default='manual', max_length=50, verbose_name='来源')),
                ('probed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='探测时间')),
                ('subnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probe_history', to='ipam.subnet')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='ipam.scantask')),
            ],
            options={
                'verbose_name': '探测历史',
                'verbose_name_plural': '探测历史',
                'ordering': ['-probed_at'],
                'indexes': [models.Index(fields=['ip_address', '-probed_at'], name='ipam_probeh_ip_addr_3dfb61_idx')],
            },
        ),
    ]
