# Generated by Django 5.2.13 on 2026-05-06 00:59

import django.db.models.deletion
from django.db import migrations, models
import ipaddress


def forward_fill_ipam(apps, schema_editor):
    AddressSpace = apps.get_model("ipam", "AddressSpace")
    Region = apps.get_model("ipam", "Region")
    VLAN = apps.get_model("ipam", "VLAN")
    Subnet = apps.get_model("ipam", "Subnet")
    IPAddress = apps.get_model("ipam", "IPAddress")

    default_region, _ = Region.objects.get_or_create(
        code="default",
        defaults={"name": "默认区域", "description": "由旧版 IPAM 自动迁移生成"},
    )

    for address_space in AddressSpace.objects.all():
        region, _ = Region.objects.get_or_create(
            code=f"as-{address_space.code}".lower()[:50],
            defaults={
                "name": address_space.name,
                "description": address_space.description,
            },
        )
        for subnet in Subnet.objects.filter(address_space_id=address_space.id):
            subnet.region_id = region.id
            subnet.name = subnet.name or subnet.cidr
            subnet.usage = subnet.usage or subnet.usage_type or ""
            try:
                network = ipaddress.ip_network(subnet.cidr, strict=False)
                subnet.total_ips = max(network.num_addresses - 2, 0)
            except ValueError:
                subnet.total_ips = 0
            subnet.used_ips = IPAddress.objects.filter(subnet_id=subnet.id).exclude(status="available").count()
            subnet.save(update_fields=["region", "name", "usage", "total_ips", "used_ips"])

    for subnet in Subnet.objects.filter(region__isnull=True):
        subnet.region_id = default_region.id
        subnet.name = subnet.name or subnet.cidr
        subnet.usage = subnet.usage or subnet.usage_type or ""
        try:
            network = ipaddress.ip_network(subnet.cidr, strict=False)
            subnet.total_ips = max(network.num_addresses - 2, 0)
        except ValueError:
            subnet.total_ips = 0
        subnet.used_ips = IPAddress.objects.filter(subnet_id=subnet.id).exclude(status="available").count()
        subnet.save(update_fields=["region", "name", "usage", "total_ips", "used_ips"])

    for subnet in Subnet.objects.exclude(legacy_vlan_id__isnull=True):
        region = Region.objects.filter(id=subnet.region_id).first() or default_region
        vlan, _ = VLAN.objects.get_or_create(
            region_id=region.id,
            vlan_id=subnet.legacy_vlan_id,
            defaults={
                "name": subnet.legacy_vlan_name or f"VLAN{subnet.legacy_vlan_id}",
                "usage": subnet.usage or subnet.usage_type or "",
                "gateway": subnet.gateway,
                "description": subnet.description,
            },
        )
        subnet.vlan_id = vlan.id
        subnet.save(update_fields=["vlan"])


def reverse_fill_ipam(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0002_initial'),
        ('dns', '0001_initial'),
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='探测状态')),
                ('response_time', models.CharField(blank=True, max_length=32, verbose_name='响应时间')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='错误信息')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='探测时间')),
            ],
            options={
                'verbose_name': '网络探测记录',
                'verbose_name_plural': '网络探测记录',
                'ordering': ['-scanned_at', 'ip_address'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='区域编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN ID')),
                ('name', models.CharField(max_length=100, verbose_name='VLAN名称')),
                ('usage', models.CharField(blank=True, max_length=100, null=True, verbose_name='用途')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLAN',
                'ordering': ['region__name', 'vlan_id', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['subnet__cidr', 'ip_address'], 'verbose_name': 'IP 地址', 'verbose_name_plural': 'IP 地址'},
        ),
        migrations.AlterModelOptions(
            name='subnet',
            options={'ordering': ['cidr'], 'verbose_name': '子网', 'verbose_name_plural': '子网'},
        ),
        migrations.AlterUniqueTogether(
            name='subnet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='bind_type',
            field=models.CharField(blank=True, choices=[('static', '静态绑定'), ('dhcp', 'DHCP'), ('manual', '手动录入')], max_length=20, null=True, verbose_name='绑定方式'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备名'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_scan_status',
            field=models.CharField(blank=True, choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], max_length=20, null=True, verbose_name='最近探测状态'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_scan_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近探测时间'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='子网名称'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='total_ips',
            field=models.IntegerField(default=0, verbose_name='IP总数'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='usage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='used_ips',
            field=models.IntegerField(default=0, verbose_name='已使用IP数'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='description',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='使用人'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('available', '空闲'), ('used', '已使用'), ('gateway', '网关'), ('disabled', '禁用'), ('reserved', '预留'), ('dhcp_dynamic', 'DHCP 动态分配'), ('dhcp_reserved', 'DHCP 固定分配')], default='available', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='ipam.subnet', verbose_name='所属子网'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='address_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='ipam.addressspace', verbose_name='地址空间'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='cidr',
            field=models.CharField(max_length=64, unique=True, verbose_name='CIDR'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='usage_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='用途(兼容)'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['last_scan_status'], name='ipam_ipaddr_last_sc_13df5b_idx'),
        ),
        migrations.AddField(
            model_name='networkscanrecord',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_records', to='ipam.subnet', verbose_name='所属子网'),
        ),
        migrations.RenameField(
            model_name='subnet',
            old_name='vlan_id',
            new_name='legacy_vlan_id',
        ),
        migrations.RenameField(
            model_name='subnet',
            old_name='vlan_name',
            new_name='legacy_vlan_name',
        ),
        migrations.AddField(
            model_name='subnet',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subnets', to='ipam.region', verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vlans', to='ipam.region', verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='ipam.vlan', verbose_name='VLAN'),
        ),
        migrations.RunPython(forward_fill_ipam, reverse_fill_ipam),
        migrations.RemoveField(
            model_name='subnet',
            name='legacy_vlan_id',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='legacy_vlan_name',
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('region', 'vlan_id')},
        ),
    ]
