# Generated by Django 5.2.13 on 2026-05-06 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_networkscanrecord_region_vlan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subnets', to='ipam.vlan', verbose_name='VLAN'),
        ),
    ]
