# Generated by Django 6.0.4 on 2026-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_add_switch_device_and_arp_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='dns_linked',
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='binding_type',
            field=models.CharField(choices=[('static', '静态绑定')], default='static', max_length=20, verbose_name='绑定方式'),
        ),
    ]
