# Generated by Django 5.2.13 on 2026-04-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('module', models.CharField(max_length=64, verbose_name='模块')),
                ('object_type', models.CharField(blank=True, max_length=64, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='对象ID')),
                ('object_name', models.CharField(blank=True, max_length=255, verbose_name='对象名称')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='请求IP')),
                ('request_method', models.CharField(blank=True, max_length=16, verbose_name='请求方法')),
                ('request_path', models.CharField(blank=True, max_length=512, verbose_name='请求路径')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='请求内容')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态')),
                ('result', models.CharField(default='success', max_length=16, verbose_name='结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
