# Generated by Django 5.2.13 on 2026-04-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=64, verbose_name='任务类型')),
                ('target_service', models.CharField(max_length=64, verbose_name='目标服务')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('canceled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='请求内容')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='响应内容')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery 任务ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统任务',
                'verbose_name_plural': '系统任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=16, verbose_name='级别')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.systemtask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'ordering': ['created_at'],
            },
        ),
    ]
