# Generated by Django 6.0.4 on 2026-04-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='地址池名称')),
                ('start_address', models.GenericIPAddressField(verbose_name='起始地址')),
                ('end_address', models.GenericIPAddressField(verbose_name='结束地址')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关')),
                ('dns_servers', models.CharField(blank=True, help_text='多个DNS用逗号分隔', max_length=500, verbose_name='DNS服务器')),
                ('lease_time', models.IntegerField(default=86400, help_text='默认86400秒(24小时)', verbose_name='租约时间(秒)')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_pools', to='ipam.subnet', verbose_name='所属子网')),
            ],
            options={
                'verbose_name': 'DHCP地址池',
                'verbose_name_plural': 'DHCP地址池',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DHCPLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC地址')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='主机名')),
                ('device_identifier', models.CharField(blank=True, max_length=200, verbose_name='设备标识')),
                ('start_time', models.DateTimeField(verbose_name='租约开始时间')),
                ('end_time', models.DateTimeField(verbose_name='租约结束时间')),
                ('status', models.CharField(choices=[('active', '活跃'), ('expired', '过期'), ('released', '已释放')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='dhcpmgr.dhcppool', verbose_name='所属地址池')),
            ],
            options={
                'verbose_name': 'DHCP租约',
                'verbose_name_plural': 'DHCP租约',
                'ordering': ['-end_time'],
            },
        ),
        migrations.CreateModel(
            name='DHCPExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.GenericIPAddressField(verbose_name='起始IP')),
                ('end_ip', models.GenericIPAddressField(verbose_name='结束IP')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='排除原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='dhcpmgr.dhcppool', verbose_name='所属地址池')),
            ],
            options={
                'verbose_name': '排除地址',
                'verbose_name_plural': '排除地址',
                'ordering': ['start_ip'],
            },
        ),
    ]
