# Generated by Django 6.0.4 on 2026-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpmgr', '0002_add_unique_active_ip_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('discover', 'DISCOVER'), ('offer', 'OFFER'), ('request', 'REQUEST'), ('ack', 'ACK'), ('nak', 'NAK'), ('release', 'RELEASE')], max_length=20, verbose_name='消息类型')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC地址')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='分配IP地址')),
                ('client_addr', models.GenericIPAddressField(verbose_name='客户端来源IP')),
                ('pool_name', models.CharField(blank=True, max_length=200, verbose_name='地址池名称')),
                ('server_id', models.GenericIPAddressField(blank=True, null=True, verbose_name='Server ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('fail', '失败'), ('ignored', '忽略')], default='success', max_length=20, verbose_name='处理结果')),
                ('detail', models.TextField(blank=True, help_text='附加信息，如失败原因等', verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': 'DHCP日志',
                'verbose_name_plural': 'DHCP日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dhcpmgr_dhc_created_315dac_idx'), models.Index(fields=['mac_address'], name='dhcpmgr_dhc_mac_add_ff42e3_idx'), models.Index(fields=['ip_address'], name='dhcpmgr_dhc_ip_addr_31999a_idx'), models.Index(fields=['msg_type'], name='dhcpmgr_dhc_msg_typ_fb9b7c_idx')],
            },
        ),
    ]
