# Generated by Django 5.2.13 on 2026-04-30 07:35

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(max_length=32, verbose_name='作用域类型')),
                ('scope_id', models.IntegerField(blank=True, null=True, verbose_name='作用域ID')),
                ('option_code', models.IntegerField(verbose_name='Option Code')),
                ('option_name', models.CharField(max_length=64, verbose_name='Option Name')),
                ('option_value', models.TextField(verbose_name='Option Value')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DHCP Option',
                'verbose_name_plural': 'DHCP Option',
            },
        ),
        migrations.CreateModel(
            name='DHCPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_start', models.GenericIPAddressField(verbose_name='起始地址')),
                ('pool_end', models.GenericIPAddressField(verbose_name='结束地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(default='enabled', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DHCP 地址池',
                'verbose_name_plural': 'DHCP 地址池',
            },
        ),
        migrations.CreateModel(
            name='DHCPProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='http://ddi-kea:8000', verbose_name='API 地址')),
                ('api_port', models.IntegerField(default=8000, verbose_name='API 端口')),
                ('service_type', models.CharField(default='dhcp4', max_length=16, verbose_name='服务类型')),
                ('timeout', models.IntegerField(default=5, verbose_name='连接超时时间')),
                ('auth_enabled', models.BooleanField(default=False, verbose_name='启用认证')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='认证用户名')),
                ('password', common.fields.EncryptedTextField(blank=True, verbose_name='认证密码')),
                ('health_check_enabled', models.BooleanField(default=True, verbose_name='启用健康检查')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Kea API 配置',
                'verbose_name_plural': 'Kea API 配置',
            },
        ),
        migrations.CreateModel(
            name='DHCPReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('mac_address', models.CharField(blank=True, max_length=32, verbose_name='MAC 地址')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='主机名')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(default='enabled', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DHCP 保留地址',
                'verbose_name_plural': 'DHCP 保留地址',
            },
        ),
        migrations.CreateModel(
            name='DHCPSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=64, verbose_name='子网')),
                ('subnet_id', models.IntegerField(unique=True, verbose_name='Kea 子网ID')),
                ('interface', models.CharField(blank=True, max_length=64, verbose_name='接口')),
                ('relay_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Relay 地址')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关')),
                ('dns_servers', models.CharField(blank=True, max_length=255, verbose_name='DNS Server')),
                ('domain_name', models.CharField(blank=True, max_length=255, verbose_name='Domain Name')),
                ('lease_time', models.IntegerField(default=3600, verbose_name='租约时间')),
                ('valid_lifetime', models.IntegerField(default=3600, verbose_name='有效生命周期')),
                ('renew_timer', models.IntegerField(default=900, verbose_name='续租时间')),
                ('rebind_timer', models.IntegerField(default=1800, verbose_name='重绑定时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DHCP 子网',
                'verbose_name_plural': 'DHCP 子网',
            },
        ),
        migrations.CreateModel(
            name='DHCPLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('mac_address', models.CharField(blank=True, max_length=32, verbose_name='MAC 地址')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='主机名')),
                ('subnet_id', models.IntegerField(verbose_name='子网ID')),
                ('state', models.CharField(blank=True, max_length=32, verbose_name='状态')),
                ('valid_lifetime', models.IntegerField(blank=True, null=True, verbose_name='有效生命周期')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('cltt', models.DateTimeField(blank=True, null=True, verbose_name='CLTT')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DHCP 租约',
                'verbose_name_plural': 'DHCP 租约',
                'indexes': [models.Index(fields=['ip_address'], name='dhcp_dhcple_ip_addr_1bce1b_idx'), models.Index(fields=['mac_address'], name='dhcp_dhcple_mac_add_73daf3_idx')],
            },
        ),
    ]
