# Generated by Django 5.2.13 on 2026-04-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhcp', '0001_initial'),
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpsubnet',
            name='ipam_subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.subnet', verbose_name='IPAM 网段'),
        ),
        migrations.AddField(
            model_name='dhcpreservation',
            name='dhcp_subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dhcp.dhcpsubnet', verbose_name='DHCP 子网'),
        ),
        migrations.AddField(
            model_name='dhcppool',
            name='dhcp_subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='dhcp.dhcpsubnet', verbose_name='DHCP 子网'),
        ),
        migrations.AlterUniqueTogether(
            name='dhcpreservation',
            unique_together={('dhcp_subnet', 'ip_address')},
        ),
    ]
