# Generated by Django 5.2.13 on 2026-05-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcpproviderconfig',
            name='service_type',
            field=models.CharField(choices=[('dhcp4', 'DHCPv4'), ('dhcp6', 'DHCPv6')], default='dhcp4', max_length=16, verbose_name='服务类型'),
        ),
    ]
