# Generated by Django 5.2.13 on 2026-05-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0003_alter_dhcpproviderconfig_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcpoption',
            name='scope_type',
            field=models.CharField(choices=[('global', '全局'), ('subnet', '子网'), ('pool', '地址池')], default='global', max_length=32, verbose_name='作用域类型'),
        ),
    ]
