# Generated by Django 5.2.13 on 2026-04-30 07:35

import common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='http://ddi-pdns:8081', verbose_name='API 地址')),
                ('api_port', models.IntegerField(default=8081, verbose_name='API 端口')),
                ('api_key', common.fields.EncryptedTextField(blank=True, verbose_name='API Key')),
                ('server_id', models.CharField(default='localhost', max_length=64, verbose_name='Server ID')),
                ('timeout', models.IntegerField(default=5, verbose_name='连接超时时间')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='启用 SSL')),
                ('health_check_enabled', models.BooleanField(default=True, verbose_name='启用健康检查')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'PowerDNS API 配置',
                'verbose_name_plural': 'PowerDNS API 配置',
            },
        ),
        migrations.CreateModel(
            name='DNSZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Zone 名称')),
                ('kind', models.CharField(choices=[('Native', 'Native'), ('Master', 'Master'), ('Slave', 'Slave')], default='Native', max_length=16, verbose_name='类型')),
                ('dnssec', models.BooleanField(default=False, verbose_name='DNSSEC')),
                ('soa_edit_api', models.CharField(blank=True, max_length=64, verbose_name='SOA Edit API')),
                ('api_rectify', models.BooleanField(default=False, verbose_name='API Rectify')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DNS Zone',
                'verbose_name_plural': 'DNS Zone',
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='记录名称')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('PTR', 'PTR'), ('SRV', 'SRV'), ('CAA', 'CAA')], max_length=16, verbose_name='记录类型')),
                ('content', models.CharField(max_length=1024, verbose_name='记录内容')),
                ('ttl', models.IntegerField(default=3600, verbose_name='TTL')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='优先级')),
                ('disabled', models.BooleanField(default=False, verbose_name='禁用')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dns.dnszone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'DNS 记录',
                'verbose_name_plural': 'DNS 记录',
            },
        ),
        migrations.CreateModel(
            name='DNSChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='请求内容')),
                ('result', models.CharField(default='success', max_length=16, verbose_name='结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dns.dnsrecord', verbose_name='记录')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dns.dnszone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'DNS 变更日志',
                'verbose_name_plural': 'DNS 变更日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dnsrecord',
            index=models.Index(fields=['record_type'], name='dns_dnsreco_record__da7d35_idx'),
        ),
        migrations.AddIndex(
            model_name='dnsrecord',
            index=models.Index(fields=['name'], name='dns_dnsreco_name_6adfed_idx'),
        ),
    ]
