# Generated by Django 5.2.13 on 2026-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_time', models.DateTimeField(verbose_name='解析时间')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端 IP')),
                ('query_name', models.CharField(max_length=255, verbose_name='查询域名')),
                ('query_type', models.CharField(blank=True, max_length=16, verbose_name='记录类型')),
                ('response_code', models.CharField(blank=True, max_length=32, verbose_name='响应码')),
                ('answer', models.TextField(blank=True, verbose_name='解析结果')),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS 服务 IP')),
                ('protocol', models.CharField(blank=True, max_length=16, verbose_name='协议')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='响应耗时')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='结果')),
                ('raw_message', models.TextField(blank=True, verbose_name='原始日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': 'DNS 解析记录',
                'verbose_name_plural': 'DNS 解析记录',
                'ordering': ['-query_time'],
                'indexes': [models.Index(fields=['-query_time'], name='dns_dnsquer_query_t_61c349_idx'), models.Index(fields=['client_ip'], name='dns_dnsquer_client__fa2e54_idx'), models.Index(fields=['query_name'], name='dns_dnsquer_query_n_54ea21_idx'), models.Index(fields=['query_type'], name='dns_dnsquer_query_t_da9405_idx'), models.Index(fields=['response_code'], name='dns_dnsquer_respons_711d22_idx')],
            },
        ),
    ]
